In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sampleChat.txt",header=None,on_bad_lines='skip',encoding='utf8')

In [3]:
df

,0,1,2,3
0,17/04/24,7:22 pm - Messages and calls are end-to-end e...,not even WhatsApp,can read or listen to them. Tap to learn more.
1,18/04/24,12:45 pm - Rubhini: <Media omitted>,NaN,NaN
2,18/04/24,12:46 pm - Rubhini: This msg I'm receiving wh...,NaN,NaN
3,18/04/24,12:50 pm - Yogana: Pls share ramisha mam numb...,NaN,NaN
4,18/04/24,12:50 pm - Rubhini: Ok mam,NaN,NaN
...,...,...,...,...
887,Currently Learning Module : Natural Language P...,NaN,NaN,NaN
888,12/08/24,8:10 pm - Rubhini: You deleted this message,NaN,NaN
889,12/08/24,8:20 pm - Rubhini: <Media omitted>,NaN,NaN
890,12/08/24,8:21 pm - Rubhini: Mam is this ok,NaN,NaN
891,12/08/24,8:48 pm - Yogana: Will check mam,NaN,NaN

In [4]:
df=df.drop(0)
columntoDel=[2,3]
df=df.drop(columns=columntoDel,axis=1)
df.columns=['Date','Chat']

In [5]:
df['Date'] = pd.to_datetime(df['Date'], format='mixed',errors='coerce')
start_date = '2024-04-18 00:00:00'
end_date = '2024-05-25 23:59:59'
df = df[(df['Date'] >= start_date) & (df['Date'] <= end_date)]

In [6]:
df

          Date                                               Chat
1   2024-04-18                12:45 pm - Rubhini: <Media omitted>
2   2024-04-18   12:46 pm - Rubhini: This msg I'm receiving wh...
3   2024-04-18   12:50 pm - Yogana: Pls share ramisha mam numb...
4   2024-04-18                         12:50 pm - Rubhini: Ok mam
5   2024-04-20                 5:42 pm - Rubhini: <Media omitted>
..         ...                                                ...
838 2024-05-08        8:25 pm - Rubhini: You deleted this message
839 2024-05-08                 8:25 pm - Rubhini: <Media omitted>
840 2024-05-08                 8:26 pm - Rubhini: <Media omitted>
841 2024-05-08                  9:15 pm - Yogana: <Media omitted>
842 2024-05-08                        9:24 pm - Rubhini: Ok mam..

[155 rows x 2 columns]

In [7]:
msg=df['Chat'].str.split('-',n=1,expand=True)
msg1=msg[1].str.split(':',n=1,expand=True)
df.loc[:,'Time']=msg[0]
df.loc[:,'Name']=msg1[0]
df.loc[:,'Chat']=msg1[1]
df=df[['Date','Time','Name','Chat']]
df

,Date,Time,Name,Chat
1,2024-04-18,12:45 pm,Rubhini,<Media omitted>
2,2024-04-18,12:46 pm,Rubhini,This msg I'm receiving while trying to login
3,2024-04-18,12:50 pm,Yogana,Pls share ramisha mam number mam
4,2024-04-18,12:50 pm,Rubhini,Ok mam
5,2024-04-20,5:42 pm,Rubhini,<Media omitted>
...,...,...,...,...
838,2024-05-08,8:25 pm,Rubhini,You deleted this message
839,2024-05-08,8:25 pm,Rubhini,<Media omitted>
840,2024-05-08,8:26 pm,Rubhini,<Media omitted>
841,2024-05-08,9:15 pm,Yogana,<Media omitted>
842,2024-05-08,9:24 pm,Rubhini,Ok mam..

In [8]:
df.drop(df[df['Chat'].str.contains(r'<\s*Media\s+omitted\s*>', na=False)].index, inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_7392\2907860454.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(df[df['Chat'].str.contains(r'<\s*Media\s+omitted\s*>', na=False)].index, inplace=True)

In [9]:
df.reset_index(drop=True, inplace=True)

In [10]:
df

,Date,Time,Name,Chat
0,2024-04-18,12:46 pm,Rubhini,This msg I'm receiving while trying to login
1,2024-04-18,12:50 pm,Yogana,Pls share ramisha mam number mam
2,2024-04-18,12:50 pm,Rubhini,Ok mam
3,2024-04-20,6:36 pm,Rubhini,Inside Downloaded resources some datasets are...
4,2024-04-20,6:50 pm,Rubhini,Ok mam.. I'll try from this datasets
...,...,...,...,...
79,2024-05-07,5:45 pm,Rubhini,Thanks for your suggestion mam
80,2024-05-07,5:47 pm,Yogana,👍
81,2024-05-08,8:25 pm,Rubhini,You deleted this message
82,2024-05-08,8:25 pm,Rubhini,You deleted this message
83,2024-05-08,9:24 pm,Rubhini,Ok mam..

In [11]:
#!pip install nltk

In [12]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [13]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [14]:
dataset=df

In [15]:
dataset.dropna(inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_7392\2639109627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.dropna(inplace=True)

In [16]:
dataset

,Date,Time,Name,Chat
0,2024-04-18,12:46 pm,Rubhini,This msg I'm receiving while trying to login
1,2024-04-18,12:50 pm,Yogana,Pls share ramisha mam number mam
2,2024-04-18,12:50 pm,Rubhini,Ok mam
3,2024-04-20,6:36 pm,Rubhini,Inside Downloaded resources some datasets are...
4,2024-04-20,6:50 pm,Rubhini,Ok mam.. I'll try from this datasets
...,...,...,...,...
79,2024-05-07,5:45 pm,Rubhini,Thanks for your suggestion mam
80,2024-05-07,5:47 pm,Yogana,👍
81,2024-05-08,8:25 pm,Rubhini,You deleted this message
82,2024-05-08,8:25 pm,Rubhini,You deleted this message
83,2024-05-08,9:24 pm,Rubhini,Ok mam..

In [17]:
sid = SentimentIntensityAnalyzer()

In [18]:
senti=sid.polarity_scores(dataset['Chat'][1])

In [19]:
senti

{'neg': 0.0, 'neu': 0.385, 'pos': 0.615, 'compound': 0.4215}

In [20]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=1.2 in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (from seaborn) (2.2.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (from seaborn) (3.7.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\envs\nlp\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)

In [24]:
def sentimentalAnalysis(data,columnname):
        
        #downloading vader_lexicon for the process
        import matplotlib.pyplot as plt
        import seaborn as sns
        "Importing Necessary Packeage"
        from nltk.sentiment.vader import SentimentIntensityAnalyzer
        sid = SentimentIntensityAnalyzer()
        
        "Deleting null pr empty value"
        data.dropna(inplace=True)
        
        "Checking for a comment"
        #sid.polarity_scores(data[columnname][93])
        
        "Creating respective columns"
        data.loc[:, 'scores'] = data[columnname].apply(lambda commentText: sid.polarity_scores(commentText))
        data.loc[:, 'compound']  = data['scores'].apply(lambda score_dict: score_dict['compound'])
        data.loc[:, 'Positive'] = data['scores'].apply(lambda score_dict: score_dict['pos'])
        data.loc[:, 'Negative']=data['scores'].apply(lambda score_dict: score_dict['neg'])
        data.loc[:, 'Neutral']  = data['scores'].apply(lambda score_dict: score_dict['neu'])
        
        "Creating final pos or neg using compound score"
        data.loc[:, 'comp_score'] = data['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')
        plt.clf()
        #comp=sns.countplot(x = 'comp_score', hue = 'Name', data = data, palette = 'magma')
        #comp.figure.savefig("date_charts.png")
        "Checking how many pos and neg"
        posneg=pd.DataFrame(data['comp_score'].value_counts())
        return posneg,data

In [25]:
pos,data_Senti=sentimentalAnalysis(dataset,columnname='Chat')

C:\Users\Admin\AppData\Local\Temp\ipykernel_7392\49951323.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

In [23]:
data_Senti

,Date,Time,Name,Chat,scores,compound,Positive,Negative,Neutral,comp_score
0,2024-04-18,12:46 pm,Rubhini,This msg I'm receiving while trying to login,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
1,2024-04-18,12:50 pm,Yogana,Pls share ramisha mam number mam,"{'neg': 0.0, 'neu': 0.385, 'pos': 0.615, 'comp...",0.4215,0.615,0.000,0.385,pos
2,2024-04-18,12:50 pm,Rubhini,Ok mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.688,0.000,0.312,pos
3,2024-04-20,6:36 pm,Rubhini,Inside Downloaded resources some datasets are...,"{'neg': 0.177, 'neu': 0.823, 'pos': 0.0, 'comp...",-0.4215,0.000,0.177,0.823,neg
4,2024-04-20,6:50 pm,Rubhini,Ok mam.. I'll try from this datasets,"{'neg': 0.0, 'neu': 0.732, 'pos': 0.268, 'comp...",0.2960,0.268,0.000,0.732,pos
...,...,...,...,...,...,...,...,...,...,...
79,2024-05-07,5:45 pm,Rubhini,Thanks for your suggestion mam,"{'neg': 0.0, 'neu': 0.58, 'pos': 0.42, 'compou...",0.4404,0.420,0.000,0.580,pos
80,2024-05-07,5:47 pm,Yogana,👍,"{'neg': 0.0, 'neu': 0.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,0.000,pos
81,2024-05-08,8:25 pm,Rubhini,You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
82,2024-05-08,8:25 pm,Rubhini,You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
83,2024-05-08,9:24 pm,Rubhini,Ok mam..,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.688,0.000,0.312,pos

In [27]:
pos

            count
comp_score
pos            82
neg             2

# Topic Modelling

In [28]:
#importing TFIDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
#creating and predicting the chat column into tfidf vector
tfidf=TfidfVectorizer(max_df=0.95,min_df=2,stop_words='english')
dtm=tfidf.fit_transform(df["Chat"])

In [49]:
tfidf

TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [30]:
from sklearn.decomposition import NMF
nmf_model=NMF(n_components=5,random_state=42)
nmf_model.fit(dtm)

NMF(n_components=5, random_state=42)

In [32]:
nmf_model.components_

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.44773224e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 6.87583759e-02, 0.00000000e+00, 1.47101870e+00,
        0.00000000e+00, 0.00000000e+00, 2.04784851e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.73961417e-07, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.17376736e-11, 1.20105307e+00, 5.73961417e-07, 3.36631674e-08,
        3.36631674e-08, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.73961417e-07, 2.84526152e-11, 0.00000000e+00, 0.00000000e+00,
        3.36631674e-08, 1.20105307e+00, 0.00000000e+00, 0.00000000e+00,
        5.23796578e-07, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 7.56170265e-11],
       [3.32369629e-02, 1.60038533e-01, 0.00000000e+00, 8.31888355e-01,
        0.00000000e+00, 0.00000000e+00, 3.32369629e-02, 2.20296637e-01,
        2.20296637e-01, 7.46429612e-01, 8.31888355e-01, 1.60038533e-01,
        3.32369629e-02, 0.00000000e+00, 2.61417856e-01, 0.00000000e+00,
        2.20296637e-01, 0.00000000e+00, 0.00000000e+00, 5.33419999e-02,
        2.18556055e-01, 0.00000000e+00, 6.35588034e-01, 1.31751520e-03,
        0.00000000e+00, 3.49032695e-01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.12880587e-01, 0.00000000e+00,
        5.20806299e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.98465304e-02, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.45798902e-05, 0.00000000e+00, 1.67729627e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.45885309e-02,
        0.00000000e+00, 1.38922801e-01, 0.00000000e+00, 1.59641870e-01,
        0.00000000e+00, 0.00000000e+00, 8.47374793e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.14674869e-02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.61261311e+00, 0.00000000e+00, 0.00000000e+00]])

In [36]:
tfidf.get_feature_names_out()

array(['announce', 'blob', 'check', 'com', 'datasets', 'deleted',
       'delighted', 'detection', 'face', 'github', 'https', 'ipynb',
       'latest', 'll', 'main', 'mam', 'mask', 'message', 'ok', 'open',
       'project', 'ramisha', 'rubhinianand', 'run', 'thanks', 'week9',
       'yes'], dtype=object)

In [37]:
topic.argsort()

array([ 0, 23, 22, 21, 20, 19, 18, 17, 16, 14, 25, 12, 13, 10,  9,  8,  7,
        6,  5,  4,  3,  2,  1, 11, 26, 15, 24], dtype=int64)

In [38]:
for index,topic in enumerate(nmf_model.components_):
    results=([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-10:]])
    print(results)

['delighted', 'deleted', 'com', 'check', 'blob', 'ipynb', 'datasets', 'll', 'mam', 'ok']
['yes', 'mask', 'face', 'detection', 'project', 'latest', 'delighted', 'announce', 'deleted', 'message']
['project', 'detection', 'face', 'mask', 'main', 'week9', 'rubhinianand', 'github', 'https', 'com']
['message', 'll', 'github', 'datasets', 'open', 'yes', 'check', 'ramisha', 'run', 'mam']
['delighted', 'deleted', 'datasets', 'com', 'check', 'blob', 'ipynb', 'yes', 'mam', 'thanks']

In [43]:
topic_results=nmf_model.transform(dtm)

In [44]:
topic_results

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.68572462e-01,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 9.82970781e-12, 0.00000000e+00, 2.05739194e-01,
        0.00000000e+00],
       [1.59631778e-01, 1.34540093e-11, 0.00000000e+00, 5.51227787e-03,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 4.22261285e-01, 0.00000000e+00,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 0.00000000e+00, 4.38113023e-01, 0.00000000e+00,
        0.00000000e+00],
       [8.65222539e-03, 0.00000000e+00, 0.00000000e+00, 5.73628843e-01,
        4.96785914e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [3.01441254e-03, 0.00000000e+00, 0.00000000e+00, 1.99981717e-01,
        5.74233341e-01],
       [0.00000000e+00, 0.00000000e+00, 5.21822276e-01, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.43998333e-01, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.21822276e-01, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.21822276e-01, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [3.01441254e-03, 0.00000000e+00, 0.00000000e+00, 1.99981717e-01,
        5.74233341e-01],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [8.65222539e-03, 0.00000000e+00, 0.00000000e+00, 5.73628843e-01,
        4.96785914e-04],
       [0.00000000e+00, 5.56657182e-08, 4.04950026e-01, 0.00000000e+00,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 5.88739000e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 5.88739000e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [8.65222539e-03, 0.00000000e+00, 0.00000000e+00, 5.73628843e-01,
        4.96785914e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 5.88739000e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 0.00000000e+00, 4.38113023e-01, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.52415106e-01,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 0.00000000e+00, 4.49813823e-01, 1.50860491e-04,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [3.01441254e-03, 0.00000000e+00, 0.00000000e+00, 1.99981717e-01,
        5.74233341e-01],
       [8.65222539e-03, 0.00000000e+00, 0.00000000e+00, 5.73628843e-01,
        4.96785914e-04],
       [0.00000000e+00, 2.61278676e-11, 0.00000000e+00, 2.93544455e-02,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [8.65222539e-03, 0.00000000e+00, 0.00000000e+00, 5.73628843e-01,
        4.96785914e-04],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 5.88739000e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 5.88739000e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 0.00000000e+00, 1.59037493e-01, 1.81850735e-01,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 2.06200271e-11, 0.00000000e+00, 3.53098465e-01,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.25470685e-02, 1.96261546e-01,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.52415106e-01,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        6.19480536e-01],
       [0.00000000e+00, 4.75825979e-08, 4.57305054e-01, 0.00000000e+00,
        0.00000000e+00],
       [8.65222539e-03, 0.00000000e+00, 0.00000000e+00, 5.73628843e-01,
        4.96785914e-04],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 4.75825979e-08, 4.57305054e-01, 0.00000000e+00,
        0.00000000e+00],
       [8.65222539e-03, 0.00000000e+00, 0.00000000e+00, 5.73628843e-01,
        4.96785914e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.25659953e-01,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [8.65222539e-03, 0.00000000e+00, 0.00000000e+00, 5.73628843e-01,
        4.96785914e-04],
       [8.65222539e-03, 0.00000000e+00, 0.00000000e+00, 5.73628843e-01,
        4.96785914e-04],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.34192535e-01,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.25659953e-01,
        0.00000000e+00],
       [0.00000000e+00, 3.85785502e-07, 5.34503440e-02, 0.00000000e+00,
        0.00000000e+00],
       [2.10250345e-01, 8.30097273e-12, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 3.85785502e-07, 5.34503440e-02, 0.00000000e+00,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [0.00000000e+00, 3.85785502e-07, 5.34503440e-02, 0.00000000e+00,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06],
       [3.01441254e-03, 0.00000000e+00, 0.00000000e+00, 1.99981717e-01,
        5.74233341e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 5.88739000e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 5.88739000e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [3.96151422e-01, 0.00000000e+00, 0.00000000e+00, 3.03507914e-04,
        6.23276881e-06]])

In [45]:
df.loc[:,"Topic"]=topic_results.argmax(axis=1)

In [46]:
df

,Date,Time,Name,Chat,scores,compound,Positive,Negative,Neutral,comp_score,Topic
0,2024-04-18,12:46 pm,Rubhini,This msg I'm receiving while trying to login,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
1,2024-04-18,12:50 pm,Yogana,Pls share ramisha mam number mam,"{'neg': 0.0, 'neu': 0.385, 'pos': 0.615, 'comp...",0.4215,0.615,0.000,0.385,pos,3
2,2024-04-18,12:50 pm,Rubhini,Ok mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.688,0.000,0.312,pos,0
3,2024-04-20,6:36 pm,Rubhini,Inside Downloaded resources some datasets are...,"{'neg': 0.177, 'neu': 0.823, 'pos': 0.0, 'comp...",-0.4215,0.000,0.177,0.823,neg,3
4,2024-04-20,6:50 pm,Rubhini,Ok mam.. I'll try from this datasets,"{'neg': 0.0, 'neu': 0.732, 'pos': 0.268, 'comp...",0.2960,0.268,0.000,0.732,pos,0
...,...,...,...,...,...,...,...,...,...,...,...
79,2024-05-07,5:45 pm,Rubhini,Thanks for your suggestion mam,"{'neg': 0.0, 'neu': 0.58, 'pos': 0.42, 'compou...",0.4404,0.420,0.000,0.580,pos,4
80,2024-05-07,5:47 pm,Yogana,👍,"{'neg': 0.0, 'neu': 0.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,0.000,pos,0
81,2024-05-08,8:25 pm,Rubhini,You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,1
82,2024-05-08,8:25 pm,Rubhini,You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,1
83,2024-05-08,9:24 pm,Rubhini,Ok mam..,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.688,0.000,0.312,pos,0

In [47]:
df["Topic"].value_counts()

Topic
0    38
3    20
2    14
1     7
4     5
Name: count, dtype: int64